package es.netmind.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2018-05-03T21:35:15.021+02:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://service.netmind.es/", name = "Echo")
@XmlSeeAlso({ObjectFactory.class})
public interface Echo {

    @WebMethod
    @RequestWrapper(localName = "echo", targetNamespace = "http://service.netmind.es/", className = "es.netmind.service.Echo_Type")
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://service.netmind.es/", className = "es.netmind.service.EchoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String echo(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
